spring.application.name=budgettracker

spring.datasource.url=${postgresql://budget_tracker_db_53vt_user:QrLWmuOc6YpslAPkw1Rj8cMd71Aj6sJT@dpg-d8m467gjs32c739p0gkg-a/budget_tracker_db_53vt}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true